services:

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - fundglide-backend
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    networks:
      - fundglide-backend
      - fundglide-mysql
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:latest
    networks:
      - fundglide-mysql
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pvictoria1992"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  fundglide-mysql:
  fundglide-backend:

volumes:
  mysql-data:

